import sqlite3
conn = sqlite3.connect('job_agent.db')
conn.row_factory = sqlite3.Row

from src.discovery.indeed import import_jobs

jobs = [
    {
        "title": "AI Engineer, Agentic AI",
        "company": "Flexday",
        "location": "Remote",
        "url": "https://to.indeed.com/aawz6fj2pt7n",
        "remote": True,
        "platform": "indeed",
        "raw_jd": "AI Engineer Agentic AI at Flexday. Remote. Design and build agentic AI systems using LLMs, LangChain, LangGraph, and multi-agent frameworks. Develop autonomous AI workflows with tool calling, memory, and reasoning capabilities. Build production-grade AI applications with RAG pipelines, vector databases, and prompt engineering. Experience with Python, OpenAI API, Anthropic Claude, and modern AI frameworks required.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "Applied AI/ML Engineer",
        "company": "Canvass Labs",
        "location": "Remote",
        "url": "https://to.indeed.com/aadcqp6fpyw7",
        "remote": True,
        "platform": "indeed",
        "raw_jd": "Applied AI/ML Engineer at Canvass Labs. Remote. $120,000 - $220,000 a year. Build and deploy machine learning models for industrial AI applications. Work with computer vision, NLP, time-series models, and deep learning on real-world data. Experience with Python, PyTorch, TensorFlow, scikit-learn required. Deploy models to production using MLOps best practices. MLflow, Docker, Kubernetes. Collaborate with data scientists and product teams.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "AI Agent Engineer",
        "company": "LaunchPad Lab",
        "location": "Chicago, IL",
        "url": "https://to.indeed.com/aa22hqhsch8m",
        "remote": False,
        "platform": "indeed",
        "raw_jd": "AI Agent Engineer at LaunchPad Lab. Chicago IL. $125,000 - $175,000 a year. Full-time. Design and build AI agent systems using LangChain, LangGraph, and LLM APIs. Develop multi-agent orchestration workflows, tool-use pipelines, and autonomous AI applications. Build RAG pipelines with vector databases Pinecone ChromaDB Weaviate. Integrate OpenAI Anthropic or open-source LLMs into production systems. Strong Python skills required. Experience with FastAPI cloud platforms AWS GCP Azure.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "AI Agent Software Engineer",
        "company": "GenuineXs LLC",
        "location": "Remote",
        "url": "https://to.indeed.com/aa8lmvw9z24v",
        "remote": True,
        "platform": "indeed",
        "raw_jd": "AI Agent Software Engineer at GenuineXs LLC. Remote. Contract. Build and deploy AI agent systems and autonomous workflows using LangChain AutoGen or CrewAI. Develop intelligent agents with tool use memory and planning capabilities. Experience with LLMs GPT-4 Claude Llama prompt engineering and RAG pipelines. Python vector databases and API integration experience required. Build multi-agent pipelines for automation and AI-driven application features.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "AI / ML Engineer",
        "company": "AssetWorks",
        "location": "Wayne, PA",
        "url": "https://to.indeed.com/aarq9sm8tcqs",
        "remote": False,
        "platform": "indeed",
        "raw_jd": "AI / ML Engineer at AssetWorks. Wayne PA. $98,701.79 - $129,850.22 a year. Full-time. Design and implement machine learning models for enterprise asset management software. Work with NLP predictive maintenance and recommendation systems. Experience with Python scikit-learn PyTorch or TensorFlow and cloud ML platforms. Deploy models to production with REST APIs FastAPI Flask. Integrate AI features into existing enterprise software products.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "Agentic AI Engineer",
        "company": "GeoDelphi",
        "location": "San Francisco, CA",
        "url": "https://to.indeed.com/aa8qftr9rp8w",
        "remote": False,
        "platform": "indeed",
        "raw_jd": "Agentic AI Engineer at GeoDelphi. San Francisco CA. Build agentic AI systems for geospatial intelligence and data analysis. Design multi-agent architectures using LangGraph LangChain or AutoGen. Develop LLM-powered pipelines with tool use RAG and autonomous reasoning. Experience with Python geospatial data and cloud platforms. Work on cutting-edge AI applications at the intersection of AI and geospatial analysis.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "AI / ML Software Engineer",
        "company": "confenn",
        "location": "Remote",
        "url": "https://to.indeed.com/aazfnpwj6lmj",
        "remote": True,
        "platform": "indeed",
        "raw_jd": "AI / ML Software Engineer at confenn. Remote. Contract. $60 - $65 an hour. Build and deploy machine learning models and AI-powered software solutions. Work with NLP computer vision or recommendation systems in production. Experience with Python PyTorch TensorFlow scikit-learn required. Develop REST APIs and microservices to serve ML models at scale. Work with MLOps tools MLflow Docker Kubernetes CI/CD pipelines. LangChain LLM integration and generative AI experience a plus.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "Data Engineer - ML/AI Data Platform",
        "company": "FEI Systems",
        "location": "Remote",
        "url": "https://to.indeed.com/aat2h66tsgxr",
        "remote": True,
        "platform": "indeed",
        "raw_jd": "Data Engineer ML/AI Data Platform at FEI Systems. Remote Columbia MD. $94,261.73 - $135,402.38 a year. Full-time. Design and build data pipelines for ML/AI model training and inference. Develop scalable ETL pipelines using Apache Spark Airflow dbt and cloud data platforms. Build feature stores and data infrastructure for machine learning models. Experience with Python SQL Spark cloud platforms AWS GCP Azure. Work with data scientists to deliver high-quality training datasets.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "Data Scientist",
        "company": "NeuroHire",
        "location": "New York, NY",
        "url": "https://to.indeed.com/aa7sggkj78db",
        "remote": False,
        "platform": "indeed",
        "raw_jd": "Data Scientist at NeuroHire. New York NY. $80,000 - $90,000 a year. Full-time. Build predictive models and machine learning solutions for HR technology and talent analytics. Develop NLP models for resume parsing job matching and candidate scoring. Experience with Python scikit-learn PyTorch pandas and SQL. Work with large datasets to build recommendation systems and classification models. Collaborate with product and engineering teams to deploy ML models to production. Strong statistical background and experience with A/B testing.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "AI/ML Engineer",
        "company": "Tata Consultancy Services",
        "location": "Jersey City, NJ",
        "url": "https://to.indeed.com/aakywc6yw2k7",
        "remote": False,
        "platform": "indeed",
        "raw_jd": "AI/ML Engineer at Tata Consultancy Services TCS. Jersey City NJ. $110,000 - $120,000 a year. Design develop and deploy machine learning and AI solutions for enterprise clients. Work with NLP computer vision and deep learning models in production environments. Experience with Python TensorFlow PyTorch scikit-learn and cloud ML platforms. Build REST APIs and MLOps pipelines for model serving and monitoring. Experience with Azure ML AWS SageMaker or GCP Vertex AI. Work with LLMs and generative AI for enterprise automation use cases.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "Mid-Level Software Engineer AI Python React",
        "company": "Alteryx",
        "location": "Remote",
        "url": "https://to.indeed.com/aars8h26lb9m",
        "remote": True,
        "platform": "indeed",
        "raw_jd": "Mid-Level Software Engineer Full Stack Python React TypeScript AI at Alteryx. Remote. $103,300 - $133,850 a year. Full-time. Build AI-powered data analytics platform features using Python React and TypeScript. Develop machine learning integrations and AI features for data science workflows. Experience with Python React TypeScript REST APIs and cloud platforms. Work with ML frameworks and LLMs to add AI-driven capabilities to analytics products. Collaborate with product teams and data scientists. Mid-level position requiring 3-5 years of software engineering experience.",
        "has_screener": False,
        "login_required": False,
    },
    {
        "title": "AI Engineer",
        "company": "Clevanoo LLC",
        "location": "Middletown, NJ",
        "url": "https://to.indeed.com/aa6j4qj27vyv",
        "remote": False,
        "platform": "indeed",
        "raw_jd": "AI Engineer at Clevanoo LLC. Middletown NJ. Contract. $50 - $52 an hour. Develop and deploy AI and machine learning solutions for enterprise clients. Build NLP models LLM integrations and AI-powered automation workflows. Experience with Python LangChain OpenAI API and transformer models required. Work with RAG pipelines vector databases and prompt engineering techniques. Deploy AI solutions using cloud platforms AWS Azure GCP and containerization Docker.",
        "has_screener": False,
        "login_required": False,
    },
]

result = import_jobs(conn, jobs)
print("Import result:", result)
conn.commit()
conn.close()
